INFO 2020-12-15 14:44:53,444 root : Сервер доступний. Час на сервері: 2020-12-15
INFO 2020-12-15 14:44:53,444 root : Запитувана сторінка: : http://localhost:8000/health/
INFO 2020-12-15 14:44:53,445 root : Відповідь сервера містить наступні поля:
INFO 2020-12-15 14:44:53,445 root : Ключ: date, Значення: 2020-12-15
INFO 2020-12-15 14:44:53,445 root : Ключ: current_page, Значення: http://localhost:8000/health/
INFO 2020-12-15 14:44:53,445 root : Ключ: server_info, Значення: 337588dbbd22
INFO 2020-12-15 14:44:53,445 root : Ключ: client_info, Значення: {'user_agent': 'python-requests/2.24.0', 'user_ip': '172.17.0.1', 'user_host': ''}
ERROR 2020-12-15 14:45:53,459 root : Сталась помилка: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd47732c190>: Failed to establish a new connection: [Errno 111] Connection refused'))
